#!/bin/bash
set -e

./script/docker-build

cp -r test/fixtures tmp
## empty so go mod tidy doesn't complain about file permissions
touch tmp/go.mod
trap "./script/clean-cluster" EXIT

docker-compose up -d charm1 charm2 charm3 minio cring
sleep 5
docker-compose run -e CHARM_HOST=cring client fs cp /usr/local/bin/charm charm:one
docker-compose run -e CHARM_HOST=cring client fs cp /usr/local/bin/charm charm:two
docker-compose run -e CHARM_HOST=cring client fs cp /usr/local/bin/charm charm:tree
docker run -v $PWD/tmp/:/mnt alpine chown -R $(id -u):$(id -u) /mnt

failed=
# Test upload was replicated to the second replica
if ! diff -r tmp/cluster/charm1/files tmp/cluster/charm2/files; then
  failed=1
fi

# Test upload was replicated to the third replica
if ! diff -r tmp/cluster/charm1/files tmp/cluster/charm3/files; then
  failed=1
fi

# Test upload was backed up
if ! diff -r tmp/cluster/charm1/files tmp/minio/charmedring; then
  failed=1
fi

trap - EXIT
./script/clean-cluster || true

if [ -n "$failed" ]; then
  echo "FAILED"
  exit 1
fi

echo "PASSED"
